remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme
title: [Enquête Collective - La Vie Sociale des Données]
description: [Nous sommes cinq étudiants de Sciences Po qui avons étudié la quantification du bonheur et les index impliqués dans le chiffrage du bien-être chez les individus. Bienvenue !]
